### ISSUE TITLE
Docs on machine users for Aperture or Library

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/docs#1173]
A customer asked:

_Good Morning Gruntworks, who (or, how) if the best way to get another service account added to our GitHub allow list for a pipeline setup please? Eg, non-human account with RSA 4k public key to access private Gruntworks github repos ?_

The answer here is a machine user, but neither our Library docs nor Aperture docs have any guidance on this.

'cc @ebeneliason to create a story.

**Comment by ZachGoldberg** [comment]
Since we now recommend the GitHub App as the primary auth mechanism for Pipelines, my read is that this issue is obviated and no longer relevant.
