### ISSUE TITLE
404 error for sample application link

### ISSUE THREAD

**Issue by racedale** [gruntwork-io/docs#1412]
the Sample Application link at the bottom of this page returns a 404 page from Github. 

https://github.com/gruntwork-io/docs/blob/master/docs/refarch/whats-this/what-is-a-reference-architecture.md

**Comment by ZachGoldberg** [comment]
Hi!  The docs are intended to be viewed at https://docs.gruntwork.io - on that site if you click on a link to a Gruntwork owned private github repository you'll get a modal letting you know that only customers have access to that content.  Sorry for any confusion!
![image](https://github.com/user-attachments/assets/e3ca0c3e-bb84-48e0-93be-cceab5566a13)
