### ISSUE TITLE
Known issues upgrading to Docusaurus 3.4

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/docs#1780]
I attempted to upgrade to Docusaurus 3.4, but hit too many roadblocks and ran out of time. I wanted to document what I've learned are some known issues with upgrading.

- **Upgrading dependencies.** [Docusaurus docs](https://docusaurus.io/docs/migration/v3) recommends updating a handful of dependencies, but we use dependencies beyond that and there are multiple `yarn` warnings when you run `yarn install`. So we need to figure out how to handle all the updated dependencies. I attempted this in https://github.com/gruntwork-io/docs/commit/ebaf937571d862afd4d50fdff15a0084293a41c4, however _I am not confident that I did this correctly._
- **Fix ES module import syntax.** In some cases, we needed to update the ES module import syntax. I fixed one example in https://github.com/gruntwork-io/docs/commit/b339762b2f32776569fe4f7c68233622332cc575.
- **Adopt breaking API changes.** In some cases, there were breaking API changes that required trivial, but non-obvious code changes. See https://github.com/gruntwork-io/docs/commit/49081d245f754db5ff2d228cd31949f2be6dbb8e.
- **Fix MDX markdown strict rendering.** The biggest source of issues was that we have both docs-site native content, and content pulled in from all our Library repos. All of this content must be compatible with MDX v3, so using simple expressions like { "a": "b" } without the `` ` `` marks surrounding it will throw errors. I fixed the native docs site content in https://github.com/gruntwork-io/docs/commit/74e14b9bebb4b1d487ed39738b457e7cd5268354, but in order to fix the generated content, we need to make direct updates in the Libary ([like this one](https://github.com/gruntwork-io/terraform-aws-data-storage/pull/475)). And then I found that docs-sourcer [doesn't always parse those updates correctly](https://github.com/gruntwork-io/docs/pull/1778#issuecomment-2176923989).

**Comment by josh-padnick** [comment]
@ZachGoldberg I think this is worth doing at some point. Could you take the lead from here? For now, I'll work on the current version of the docs site.

**Comment by ZachGoldberg** [comment]
We're on 3.6 now!
