### ISSUE TITLE
Stay up to date page makes automatic changes we don't want to commit

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/docs#1781]
Every time I run the docs site locally, I get an update to docs/guides/stay-up-to-date/index.md that looks like this:

<img width="867" alt="image" src="https://github.com/gruntwork-io/docs/assets/4295964/6159e437-4151-4dc7-bb7b-7335d7f51a85">

In the past, committing this change caused an issue, but I haven't found a way to hide it with `.gitignore` and I'm not sure why it behaves this way in the first place.

**Comment by ZachGoldberg** [comment]
No longer relavent with modern DX
