### ISSUE TITLE
Incomplete sentence

### ISSUE THREAD

**Issue by Andrew-Wichmann** [gruntwork-io/docs#51]
I'm not sure where to raise this issue; here seems best. Please don't bite my head off. xD

There is a sentence in [this section of the gruntwork guides](https://gruntwork.io/guides/networking/how-to-deploy-production-grade-vpc-aws#nacls) under Stateful/Stateless that goes...

> Security groups are stateful, so if have a rule that allows an inbound connection on, say, port 80...

it should probably read

> Security groups are stateful, so if _a security group has_ a rule that allows an inbound connection on, say, port 80...

**Comment by bwhaley** [comment]
Thanks for the report! Just opened https://github.com/gruntwork-io/gruntwork-io.github.io/pull/431 to get that fixed.
